language: java
jdk: 
- oraclejdk7
- openjdk6

script: mvn verify

# deploy if the first job is successful; should be replaced by an after_all_success if travis finally supports it
after_success: 
- if [[ $TRAVIS_JOB_NUMBER == *1 ]]; then mvn -DskipTests deploy --settings deploysettings.xml; fi

env: 
  global: 
  - secure: Zg9E6NZU6Jq322TuvMnnCwHv/e9NvokZlrIHk/WTHGY6n7l6mSjfhWzvPzCWJ4ITwzdCBwoOrN0Y/ecVEu6gfJds47kGF7UAeVpWkmGGQSTL3BlDXZvCEJ2GTJXV6Hnt2VnWecjXWfc0YbFAy66cQ1zW1rKkTFgWHB2XQZFBBPA=
  - secure: TzwXeR3qq73LJ9DGylNDNzfLzTFkINC+gPxkfPcMUuyG+iR2xyVq3/ocZgBMUc5OEbXj55o1Xl1Oev8kXOfAStyuHG7oAb5VDMPYgKwRumNckBLgDE+EYyXZwmwSO1T1WgFBTojnVOhIJfcE2kE8LLGuW8aetOqh366SD7UXgX8=

